# Docker Compose configuration for frontend, backend, and PostgreSQL
version: '3.8'
services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
